### ISSUE TITLE
end

### ISSUE THREAD

**Issue by Abdurahmanm2020** [Abdurahmanm2020/music-maker#1]
there Would of been a end button but I did not have time to make is so now there is none 

and I don't know how to add it when it is up on git hub 

pleas help !!!

**Comment by byabbas** [comment]
> there Would of been a end button but I did not have time to make is so now there is none
> 
> and I don't know how to add it when it is up on git hub
> 
> pleas help !!!

You edit it then implement what ever you want to.

**Comment by Abdurahmanm2020** [comment]
thank Abbas for the help

any one have more to add
